export interface ContentNode {
  id: string;
  title: string;
  color: string;
  gradient: string;
  theme: string;
  children?: ContentNode[];
  content?: {
    intro?: string;
    detail?: string;
    highlights?: string[];
    applications?: string[];
    sourceLabel?: string;
    image?: string;
    video?: string;
    relatedItems?: string[];
  };
}

export const contentData: ContentNode[] = [
  {
    id: 'ai',
    title: 'Artificial Intelligence',
    color: '#FF3344',
    gradient: 'from-red-500 to-orange-500',
    theme: 'ai',
    content: {
      intro: 'AI maakt sensordata, kennis en procesinformatie bruikbaar voor betere beslissingen in de maakindustrie.',
      detail: 'Binnen iXperium Smart Industry wordt AI gekoppeld aan toegepast data science onderzoek, kennisplatforms en demonstraties waarin bedrijven kunnen experimenteren met data, algoritmes en mensgerichte besluitvorming.',
      highlights: ['HAN Datalab', 'Applied Data Science & AI', 'Data & Knowledge Engineering'],
      applications: ['Predictive maintenance', 'Kennisplatforms', 'Procesoptimalisatie'],
      sourceLabel: 'HAN iXperium Smart Industry, ADS&AI en DKE',
      relatedItems: ['Datalab', 'Toolkit', 'Cases'],
    },
    children: [
      {
        id: 'ai-adsai',
        title: 'Lectoraat Applied Data Science & AI',
        color: '#FF3344',
        gradient: 'from-red-400 to-red-600',
        theme: 'ai',
        content: {
          intro: 'Praktijkgericht onderzoek naar data en kunstmatige intelligentie voor maatschappelijke en industriële innovatie.',
          detail: 'Het lectoraat bouwt kennis over data en AI op en vertaalt die naar projecten zoals Roadsense, kennisplatforms, DEMAND en Operations Digital Twin toepassingen voor mkb-maakbedrijven.',
          highlights: ['Gestart in 2024', 'Roadsense', 'Operations Digital Twin'],
          applications: ['Sensordata benutten', 'Onderhoud voorspellen', 'Realtime planning'],
          sourceLabel: 'HAN Applied Data Science & AI',
          relatedItems: ['Datalab', 'AI in de praktijk'],
        },
      },
      {
        id: 'ai-dke',
        title: 'Lectoraat DKE',
        color: '#FFA033',
        gradient: 'from-orange-400 to-orange-600',
        theme: 'ai',
        content: {
          intro: 'Data & Knowledge Engineering richt zich op data, informatie en expliciete kennis in systemen.',
          detail: 'Het lectoraat onderzoekt hoe organisaties data en kennis doelbewust kunnen opsporen, representeren, valideren, beheren en toepassen. Denk aan knowledge graphs, text mining, LLMs en dialooginterfaces.',
          highlights: ['Knowledge graphs', 'Text mining', 'Dialogue systems'],
          applications: ['Kennissystemen', 'Datamanagement', 'Conceptueel modelleren'],
          sourceLabel: 'HAN Data & Knowledge Engineering',
          relatedItems: ['Toolkit', 'Cases'],
        },
      },
      {
        id: 'ai-praktijk',
        title: 'AI in de praktijk',
        color: '#FF4400',
        gradient: 'from-red-500 to-orange-500',
        theme: 'ai',
        content: {
          intro: 'Praktische AI laat bezoekers en bedrijven ervaren wat algoritmes doen met echte vraagstukken.',
          detail: 'De focus ligt op concrete demonstraties: patronen herkennen, voorspellen, aanbevelen en beslissingen ondersteunen zonder de menselijke maat uit het oog te verliezen.',
          highlights: ['Demonstraties', 'Mensgerichte AI', 'Meetbare waarde'],
          applications: ['Kwaliteitscontrole', 'Slimme dashboards', 'Beslisondersteuning'],
          sourceLabel: 'iXperium Smart Industry projectdocument',
          relatedItems: ['Datalab', 'Cases'],
        },
      },
      {
        id: 'ai-datalab',
        title: 'Datalab',
        color: '#FFD700',
        gradient: 'from-yellow-400 to-orange-400',
        theme: 'ai',
        content: {
          intro: 'In het HAN Datalab ervaren bezoekers data science en AI aan de hand van datasets en praktijkcases.',
          detail: 'Het lab maakt data tastbaar: van sensordata tot modellen die onderhoud, kwaliteit of procesgedrag kunnen voorspellen. Het Roadsense voorbeeld laat zien hoe trailerdata kan bijdragen aan onderhoud en wegkwaliteit.',
          highlights: ['Data science demo', 'Roadsense', 'Experimenteren met data'],
          applications: ['Voorspellend onderhoud', 'Procesinzicht', 'Data literacy'],
          sourceLabel: 'HAN opening iXperium Smart Industry',
          relatedItems: ['Toolkit', 'AI in de praktijk'],
        },
      },
      {
        id: 'ai-toolkit',
        title: 'Toolkit',
        color: '#C69E00',
        gradient: 'from-yellow-600 to-orange-500',
        theme: 'ai',
        content: {
          intro: 'De AI-toolkit vertaalt onderzoek en labs naar toepasbare stappen, methodes en experimenten.',
          detail: 'Bedrijven kunnen de toolkit gebruiken om van vraag naar dataset, modelkeuze, prototype en validatie te bewegen. De nadruk ligt op kleinschalig starten en snel leren.',
          highlights: ['Vraagarticulatie', 'Prototype-aanpak', 'Validatie'],
          applications: ['AI-scan', 'Modelverkenning', 'Datakwaliteit'],
          sourceLabel: 'iXperium Smart Industry projectdocument',
          relatedItems: ['Cases', 'Datalab'],
        },
      },
      {
        id: 'ai-cases',
        title: 'Cases',
        color: '#FB3E0F',
        gradient: 'from-orange-500 to-red-500',
        theme: 'ai',
        content: {
          intro: 'Cases laten zien hoe AI in echte productie- en serviceprocessen waarde kan toevoegen.',
          detail: 'De caselaag verbindt labs, lectoraten en bedrijven. Daardoor wordt zichtbaar welke data nodig is, welke beslissing verbeterd wordt en hoe de oplossing praktisch getest kan worden.',
          highlights: ['Mkb-context', 'Onderzoek plus onderwijs', 'Meetbaar experiment'],
          applications: ['Onderhoud', 'Planning', 'Kwaliteit'],
          sourceLabel: 'HAN iXperium Smart Industry',
          relatedItems: ['Toolkit', 'AI in de praktijk'],
        },
      },
    ],
  },
  {
    id: 'xr',
    title: 'XR & Human Machine Interaction',
    color: '#46B469',
    gradient: 'from-green-500 to-lime-500',
    theme: 'xr',
    content: {
      intro: 'XR en HMI maken complexe technologie zichtbaar, begrijpelijk en bruikbaar voor mensen op de werkvloer.',
      detail: 'Het thema combineert immersive media, usability onderzoek en flexibele werkinstructies. De vraag is steeds hoe nieuwe digitale toepassingen aansluiten bij houding, vaardigheden, voorkeuren en behoeften van gebruikers.',
      highlights: ['User Experience Lab', 'Media Design', 'Flexibele werkinstructies'],
      applications: ['AR-instructies', 'Usability tests', '3D visualisaties'],
      sourceLabel: 'HAN Media Design en iXperium Smart Industry',
      relatedItems: ['Usability Lab', 'Toolkit', 'Cases'],
    },
    children: [
      {
        id: 'xr-media',
        title: 'Lectoraat Media Design',
        color: '#46B469',
        gradient: 'from-green-400 to-green-600',
        theme: 'xr',
        content: {
          intro: 'Media Design onderzoekt hoe digitale toepassingen begrijpelijk, prettig en betekenisvol worden.',
          detail: 'Het lectoraat werkt voor en met eindgebruikers. Nieuwe toepassingen met geluid, spraak, tast en 3D-visualisaties worden snel geprototyped, gesimuleerd en getest in het User Experience Lab.',
          highlights: ['Menselijke maat', 'Ontwerpend onderzoek', 'User Experience Lab'],
          applications: ['Prototypes', 'Gebruikersonderzoek', 'XR scenario tests'],
          sourceLabel: 'HAN Media Design',
          relatedItems: ['Usability Lab', 'Toolkit'],
        },
      },
      {
        id: 'xr-lean',
        title: 'Lectoraat LEAN',
        color: '#A0EA00',
        gradient: 'from-lime-400 to-green-500',
        theme: 'xr',
        content: {
          intro: 'Lean / World Class Performance verbindt slim organiseren met smart technologie in productdesign en manufacturing.',
          detail: 'Voor XR en HMI betekent dit: digitale ondersteuning die het werk beter, sneller of betrouwbaarder maakt zonder de operator uit het proces te halen.',
          highlights: ['Smart Lean', 'Productontwikkeling', 'Continu verbeteren'],
          applications: ['Werkplekinstructies', 'Procesverbetering', 'Operator support'],
          sourceLabel: 'HAN Lean / World Class Performance',
          relatedItems: ['Cases', 'Toolkit'],
        },
      },
      {
        id: 'xr-usability',
        title: 'Usability Lab',
        color: '#6DB600',
        gradient: 'from-lime-500 to-green-600',
        theme: 'xr',
        content: {
          intro: 'Het Usability Lab maakt zichtbaar hoe mensen met digitale interfaces en nieuwe technologie omgaan.',
          detail: 'In het iXperium kunnen bedrijven ervaren hoe bijvoorbeeld eyetracking en gebruikerstests helpen om interfaces, instructies en XR-toepassingen beter te ontwerpen.',
          highlights: ['Eyetracking', 'Gebruikerstests', 'Experience lab'],
          applications: ['Interfacevalidatie', 'AR-bril onderzoek', 'Werkplekontwerp'],
          sourceLabel: 'HAN iXperium Smart Industry en Media Design',
          relatedItems: ['Lectoraat Media Design', 'Cases'],
        },
      },
      {
        id: 'xr-toolkit',
        title: 'Toolkit',
        color: '#9ABF49',
        gradient: 'from-lime-400 to-green-400',
        theme: 'xr',
        content: {
          intro: 'De XR/HMI-toolkit helpt om van werkproces naar prototype, test en implementatie te gaan.',
          detail: 'De toolkit bundelt ontwerpvragen, testvormen en technische keuzes voor AR, VR, scherminterfaces en instructies die in productieomgevingen bruikbaar moeten blijven.',
          highlights: ['Prototype canvas', 'Gebruikertest', 'Technologiekeuze'],
          applications: ['AR workflow', 'VR training', 'HMI review'],
          sourceLabel: 'iXperium Smart Industry projectdocument',
          relatedItems: ['Usability Lab', 'Cases'],
        },
      },
      {
        id: 'xr-cases',
        title: 'Cases',
        color: '#2E8B57',
        gradient: 'from-green-600 to-emerald-600',
        theme: 'xr',
        content: {
          intro: 'XR-cases tonen hoe ontwerp, mens en machine samenkomen in concrete werksituaties.',
          detail: 'Voorbeelden zijn flexibele werkinstructies, slimme brillen, interfaceonderzoek en prototypes die medewerkers ondersteunen in omgevingen met veel variatie.',
          highlights: ['Slimme brillen', 'Flexibele instructies', 'Praktijkpartners'],
          applications: ['Assemblage', 'Training', 'Kwaliteitsborging'],
          sourceLabel: 'HAN Media Design onderzoek',
          relatedItems: ['Toolkit', 'Lectoraat Media Design'],
        },
      },
    ],
  },
  {
    id: 'twin',
    title: 'Digital Twin',
    color: '#1E90FF',
    gradient: 'from-blue-500 to-cyan-500',
    theme: 'twin',
    content: {
      intro: 'Digital twins verbinden fysieke processen, data en simulatie tot een actueel beeld van productie en logistiek.',
      detail: 'Binnen Smart Industry wordt digital twinning toegepast in de USAC, operations digital twins en studentprojecten rond robots. Zo kunnen scenario’s, planning en procesveranderingen veilig worden onderzocht.',
      highlights: ['Operations Digital Twin', 'USAC', 'Delta robot simulatie'],
      applications: ['Realtime planning', 'What-if simulatie', 'Procesbesturing'],
      sourceLabel: 'HAN ADS&AI, USAC en Digital Twin artikelen',
      relatedItems: ['USAC', 'Toolkit', 'Cases'],
    },
    children: [
      {
        id: 'twin-lean',
        title: 'Lectoraat LEAN',
        color: '#1E90FF',
        gradient: 'from-blue-400 to-blue-600',
        theme: 'twin',
        content: {
          intro: 'Lean gebruikt digital twins om productieprocessen continu te verbeteren en slim te organiseren.',
          detail: 'In de USAC wordt onderzocht hoe smart technologie werknemers kan ondersteunen en hoe digital twins helpen bij planning, doorvoer en procesinzicht.',
          highlights: ['Smart Lean', 'USAC', 'Procesverbetering'],
          applications: ['Doorlooptijd', 'Capaciteitsbalans', 'Werkverdeling'],
          sourceLabel: 'HAN Lean / World Class Performance',
          relatedItems: ['USAC', 'Toolkit'],
        },
      },
      {
        id: 'twin-dke',
        title: 'Lectoraat DKE',
        color: '#1C92AF',
        gradient: 'from-cyan-500 to-blue-500',
        theme: 'twin',
        content: {
          intro: 'DKE brengt de data- en kenniskant van digital twins in beeld.',
          detail: 'Een goede twin vraagt om heldere datamodellen, expliciete kennis, conceptueel modelleren en bruikbare visualisaties. DKE levert methoden om die informatie betrouwbaar te beheren.',
          highlights: ['Datamodellen', 'Kennisrepresentatie', 'Visualisaties'],
          applications: ['Twin architectuur', 'Conceptueel model', 'Kennisplatform'],
          sourceLabel: 'HAN Data & Knowledge Engineering',
          relatedItems: ['Lectoraat ADSAI', 'Cases'],
        },
      },
      {
        id: 'twin-adsai',
        title: 'Lectoraat ADSAI',
        color: '#0088FF',
        gradient: 'from-blue-500 to-cyan-600',
        theme: 'twin',
        content: {
          intro: 'Applied Data Science & AI ontwikkelt onder meer Operations Digital Twin toepassingen voor mkb-maakbedrijven.',
          detail: 'De focus ligt op realtime procesbeheersing: optimaal plannen, reageren op wijzigingen en data gebruiken om doorlooptijden kort en betrouwbaar te houden.',
          highlights: ['Operations Digital Twin', 'Realtime procesbeheersing', 'Mkb-maakbedrijven'],
          applications: ['Planning', 'Scenario-analyse', 'Beslisondersteuning'],
          sourceLabel: 'HAN Applied Data Science & AI',
          relatedItems: ['USAC', 'Toolkit'],
        },
      },
      {
        id: 'twin-usac',
        title: 'USAC',
        color: '#20B2AA',
        gradient: 'from-teal-400 to-cyan-500',
        theme: 'twin',
        content: {
          intro: 'De Smart U-Shaped Assembly Cell is een leer- en probeeromgeving voor smart technologie in assemblage.',
          detail: 'De USAC combineert Lean principes met technologie zoals AR-instructies, cobots, AGV-ideeen en digital twins. Bedrijven, studenten en onderzoekers testen er hoe processen beter kunnen werken.',
          highlights: ['U-vormige cel', 'Digital twin', 'Cobots'],
          applications: ['Assemblage met hoge variatie', 'Operator support', 'Doorvoeroptimalisatie'],
          sourceLabel: 'HAN USAC artikelen',
          relatedItems: ['Toolkit', 'Cases'],
        },
      },
      {
        id: 'twin-toolkit',
        title: 'Toolkit',
        color: '#87CEFA',
        gradient: 'from-sky-300 to-blue-400',
        theme: 'twin',
        content: {
          intro: 'De Digital Twin-toolkit helpt om fysieke processen te vertalen naar data, modellen en simulaties.',
          detail: 'De toolkit ondersteunt de stap van digital shadow naar digital twin: meten, modelleren, visualiseren, simuleren en vervolgens terugkoppelen naar de echte werkvloer.',
          highlights: ['Digital shadow', 'Modelvorming', 'Simulatie'],
          applications: ['Proceskaart', 'Sensorplan', 'Twin prototype'],
          sourceLabel: 'iXperium Smart Industry projectdocument',
          relatedItems: ['Cases', 'USAC'],
        },
      },
      {
        id: 'twin-cases',
        title: 'Cases',
        color: '#3022B2',
        gradient: 'from-blue-700 to-indigo-600',
        theme: 'twin',
        content: {
          intro: 'Digital Twin-cases tonen hoe simulatie en echte machines elkaar kunnen versterken.',
          detail: 'Een voorbeeld is het studentproject rond de Delta X2 robot, waarin Unity-simulaties worden gesynchroniseerd met de echte robot om een digitale tweeling of schaduw te maken.',
          highlights: ['Delta X2 robot', 'Unity simulatie', 'Multidisciplinair team'],
          applications: ['Robot simulatie', 'Virtuele testomgeving', 'Industriele demonstratie'],
          sourceLabel: 'HAN Digital Twin delta robot',
          relatedItems: ['Toolkit', 'Lectoraat LEAN'],
        },
      },
    ],
  },
  {
    id: 'rapid',
    title: 'Rapid Prototyping & Additive Manufacturing',
    color: '#E9CE03',
    gradient: 'from-yellow-400 to-orange-500',
    theme: 'rapid',
    content: {
      intro: 'Rapid prototyping en additive manufacturing brengen ideeen snel van digitaal ontwerp naar tastbaar prototype.',
      detail: 'In het iXperium en HAN FabLab ervaren bedrijven hoe 3D-printen, digitale fabricage en materiaalexperimenten kunnen helpen bij prototyping, maatwerk en steeds vaker ook industriele toepassingen.',
      highlights: ['HAN FabLab', '3D-printers', 'Design-build-test'],
      applications: ['Functionele prototypes', 'Maatwerk', 'Kleine series'],
      sourceLabel: 'HAN Additive Manufacturing en iXperium',
      relatedItems: ['FabLab', 'Toolkit', 'Cases'],
    },
    children: [
      {
        id: 'rapid-fablab',
        title: 'FabLab',
        color: '#E9CE03',
        gradient: 'from-yellow-400 to-yellow-600',
        theme: 'rapid',
        content: {
          intro: 'Het HAN FabLab is de digitale werkplaats voor maken, testen en leren met fabricagetechnieken.',
          detail: 'Tijdens de iXperium-tour staan in het FabLab fabricagetechnieken zoals 3D-printen centraal. Bedrijven kunnen er zelf ervaren hoe grondstoffen en ontwerpen tot prototypes worden verwerkt.',
          highlights: ['Digitale werkplaats', '3D-printen', 'Materiaalexperiment'],
          applications: ['Prototypebouw', 'Onderwijsprojecten', 'Maakindustrie demo'],
          sourceLabel: 'HAN iXperium Smart Industry en FabLab',
          relatedItems: ['Toolkit', 'Cases'],
        },
      },
      {
        id: 'rapid-toolkit',
        title: 'Toolkit',
        color: '#FFA914',
        gradient: 'from-orange-400 to-yellow-500',
        theme: 'rapid',
        content: {
          intro: 'De toolkit helpt om van ontwerpprobleem naar maakbaar prototype te gaan.',
          detail: 'De aanpak combineert materiaalkeuze, ontwerpregels, testscenario’s en snelle iteraties. Zo wordt additive manufacturing praktisch en toepasbaar voor mkb-vragen.',
          highlights: ['Materiaalkeuze', 'Ontwerpregels', 'Itereren'],
          applications: ['Maakbaarheidsscan', 'Prototype sprint', 'Testopstelling'],
          sourceLabel: 'iXperium Smart Industry projectdocument',
          relatedItems: ['FabLab', 'Cases'],
        },
      },
      {
        id: 'rapid-cases',
        title: 'Cases',
        color: '#DBB600',
        gradient: 'from-yellow-500 to-amber-600',
        theme: 'rapid',
        content: {
          intro: 'Cases laten zien waar digitale fabricage verschil maakt: sneller leren, beter testen en slimmer produceren.',
          detail: 'Additive manufacturing ontwikkelt zich van niche voor prototyping naar hoogwaardige industriele toepassingen. De cases tonen hoe samenwerking en kennisdeling die stap toegankelijker maken.',
          highlights: ['Van niche naar industrie', 'Kennisdeling', 'Testen met gebruikers'],
          applications: ['3D-geprinte hulpmiddelen', 'Productvalidatie', 'Maatwerkproductie'],
          sourceLabel: 'HAN Additive Manufacturing',
          relatedItems: ['Toolkit', 'FabLab'],
        },
      },
    ],
  },
  {
    id: 'robotics',
    title: 'Robotics',
    color: '#FF2AD4',
    gradient: 'from-fuchsia-500 to-cyan-400',
    theme: 'robotics',
    content: {
      intro: 'Robotics verbindt mobiele robots, cobots, autonome voertuigen en mens-machine samenwerking in echte labs.',
      detail: 'Robotics@HAN biedt faciliteiten voor onderzoek en onderwijs: serverkracht, Mobile Robotics Lab, Lab Autonomous Vehicles, zorgrobotica en USAC-opstellingen met delta pickers en cobots.',
      highlights: ['Mobile Robotics Lab', 'Autonomous Vehicles', 'Cobots & USAC'],
      applications: ['ROS ontwikkeling', 'Autonoom testen', 'Slimme assemblage'],
      sourceLabel: 'Robotics@HAN faciliteiten',
      relatedItems: ['Mobile Robotics Lab', 'Cobots & USAC', 'Test- en meetsystemen'],
    },
    children: [
      {
        id: 'robotics-servers',
        title: 'Robotics@HAN servers',
        color: '#FF2AD4',
        gradient: 'from-fuchsia-500 to-purple-600',
        theme: 'robotics',
        content: {
          intro: 'On-premise computerkracht voor robotica onderwijs, onderzoek en projectpartners.',
          detail: 'De servers ondersteunen simulaties, AI training, robotbesturing, Hardware in the Loop en digital twinning. Ze zijn breedbandig verbonden met het Mobile Robotics Lab en Lab Autonomous Vehicles.',
          highlights: ['Control Center', 'AI training', 'Hardware in the Loop'],
          applications: ['Simulatie', 'Robotbesturing', 'Digital twinning'],
          sourceLabel: 'Robotics@HAN faciliteiten',
          relatedItems: ['Mobile Robotics Lab', 'Lab Autonomous Vehicles'],
        },
      },
      {
        id: 'robotics-mobile-lab',
        title: 'Mobile Robotics Lab',
        color: '#00F5FF',
        gradient: 'from-cyan-300 to-fuchsia-500',
        theme: 'robotics',
        content: {
          intro: 'Werkplekken en een testruimte voor mobiele robots met nauwkeurige realtime lokalisatie.',
          detail: 'Het lab gebruikt OptiTrack motion capture. Lokalisatie kan via wifi als ROS topic naar robots worden gepubliceerd, eventueel als ge-emuleerde GPS. PTZ-camera’s maken tests op afstand zichtbaar.',
          highlights: ['OptiTrack', 'ROS topics', 'PTZ camera’s'],
          applications: ['Robotlokalisatie', 'Testopnames', 'Mobiele robotontwikkeling'],
          sourceLabel: 'Robotics@HAN faciliteiten',
          relatedItems: ['Robotics@HAN servers', 'Test- en meetsystemen'],
        },
      },
      {
        id: 'robotics-autonomous-vehicles',
        title: 'Lab Autonomous Vehicles',
        color: '#9D4DFF',
        gradient: 'from-violet-500 to-cyan-400',
        theme: 'robotics',
        content: {
          intro: 'Garageruimte en buitentestlocaties voor full-scale autonome voertuigen en grotere mobiele robots.',
          detail: 'Het lab heeft grote roldeuren, toegang tot buitentests en een nabij parkeerdek van 165 bij 10 meter. Een LiDAR-gebaseerde referentiekaart kan gebruikt worden voor lokalisatie.',
          highlights: ['Full-scale testen', 'Buitenterrein', 'LiDAR referentiekaart'],
          applications: ['Autonome voertuigen', 'Mobiele robots', 'Navigatievalidatie'],
          sourceLabel: 'Robotics@HAN faciliteiten',
          relatedItems: ['HAN Streetdrone', 'Mobile Robotics Lab'],
        },
      },
      {
        id: 'robotics-cobots-usac',
        title: 'Cobots & USAC',
        color: '#C7FF2E',
        gradient: 'from-lime-300 to-fuchsia-500',
        theme: 'robotics',
        content: {
          intro: 'De USAC is een slimme productieomgeving met robotica-oplossingen voor flexibele assemblage.',
          detail: 'In de USAC wordt gewerkt met delta pickers, cobots, vision-systemen, grijpers en een gekoppelde IT-structuur. Bedrijven en studenten leren er hoe automatisering werkt in productie met veel variatie.',
          highlights: ['Delta pickers', 'Cobots', 'Operations digital twin'],
          applications: ['Monteren', 'Controleren', 'Proces stroomlijnen'],
          sourceLabel: 'HAN USAC en cobot-artikel',
          relatedItems: ['Robotics@HAN servers', 'iXperium Smart Industry'],
        },
      },
      {
        id: 'robotics-health-carebots',
        title: 'Zorgrobotica',
        color: '#FF6BE8',
        gradient: 'from-pink-400 to-cyan-400',
        theme: 'robotics',
        content: {
          intro: 'Zorgrobotica onderzoekt het samenspel tussen technologie, acceptatie en mensgerichte zorgprocessen.',
          detail: 'Robotics@HAN koppelt zorgspecialisten, technici, IT’ers en processpecialisten. Studenten bouwden bijvoorbeeld een prototype logistieke zorgrobot als testplatform voor CareBOTS.',
          highlights: ['CareBOTS', 'Mens-machine acceptatie', 'Logistieke zorgrobot'],
          applications: ['Zorglogistiek', 'Robotacceptatie', 'SLAM en navigatie'],
          sourceLabel: 'Robotics@HAN',
          relatedItems: ['iXperium Health', 'Test- en meetsystemen'],
        },
      },
      {
        id: 'robotics-test-systems',
        title: 'Test- en meetsystemen',
        color: '#50FFB8',
        gradient: 'from-emerald-300 to-fuchsia-500',
        theme: 'robotics',
        content: {
          intro: 'Meet- en testsystemen maken robotgedrag controleerbaar in lab- en praktijkscenario’s.',
          detail: 'Denk aan mobiele motion capture, RTK-GPS, sensorplatforms, dummies voor verkeersscenario’s en perception kits. Deze middelen helpen om testen herhaalbaar en uitlegbaar te maken.',
          highlights: ['Motion capture', 'RTK-GPS', 'Perception kits'],
          applications: ['Validatie', 'Scenario testen', 'Sensorvergelijking'],
          sourceLabel: 'Robotics@HAN faciliteiten',
          relatedItems: ['Mobile Robotics Lab', 'Lab Autonomous Vehicles'],
        },
      },
    ],
  },
];
