export interface ContentNode {
  id: string;
  title: string;
  color: string;
  gradient: string;
  theme: string;
  children?: ContentNode[];
  content?: {
    intro?: string;
    detail?: string;
    highlights?: string[];
    applications?: string[];
    sourceLabel?: string;
    image?: string;
    video?: string;
    relatedItems?: string[];
  };
}

const oldImages = {
  aiMain: new URL('../../OUD/ixperium-smart-industry/content/ai/ai_main.jpg', import.meta.url).href,
  aiRoadsense: new URL('../../OUD/ixperium-smart-industry/content/cases/ai/truck.jpg', import.meta.url).href,
  aiTransport: new URL('../../OUD/ixperium-smart-industry/content/ai/transport_sector.jpg', import.meta.url).href,
  xrHeadset: new URL('../../OUD/ixperium-smart-industry/content/xr/vr_headset.jpg', import.meta.url).href,
  xrAlliander: new URL('../../OUD/ixperium-smart-industry/content/cases/xrhmi/alliander-xr2.jpg', import.meta.url).href,
  xrAllianderDetail: new URL('../../OUD/ixperium-smart-industry/content/cases/xrhmi/alliander-xr.jpg', import.meta.url).href,
  twinMain: new URL('../../OUD/ixperium-smart-industry/content/digitaltwin/digital_twin.jpg', import.meta.url).href,
  twinGoma: new URL('../../OUD/ixperium-smart-industry/content/cases/digitaltwin/goma1.jpg', import.meta.url).href,
  twinGomaDetail: new URL('../../OUD/ixperium-smart-industry/content/cases/digitaltwin/goma2.jpg', import.meta.url).href,
  twinResult: new URL('../../OUD/ixperium-smart-industry/content/cases/digitaltwin/result_hu7398049482760340400.webp', import.meta.url).href,
  smartIndustry: new URL('../../OUD/ixperium-smart-industry/content/smartindustry/smart_industry.jpg', import.meta.url).href,
  smartIndustryWide: new URL('../../OUD/ixperium-smart-industry/content/smartindustry/smart_industry1.jpg', import.meta.url).href,
  additivePrinter: new URL('../../OUD/ixperium-smart-industry/content/additive/3d_printer.jpg', import.meta.url).href,
  additiveCase: new URL('../../OUD/ixperium-smart-industry/content/cases/rpam/lalique1.jpg', import.meta.url).href,
} as const;

const hanImages = {
  erwinFolmer: 'https://www.han.nl/images/brandspot/new/2023/12/20/portretfoto-erwin-folmer-header_2023_d5962610.jpg',
  stijnHoppenbrouwers: 'https://www.han.nl/images/brandspot/new/2022/06/22/lectoraat-mbis-stijn-hoppenbrouwers_2022_417929.jpg',
} as const;

export const contentData: ContentNode[] = [
  {
    id: 'ai',
    title: 'Artificial Intelligence',
    color: '#FF3344',
    gradient: 'from-red-500 to-orange-500',
    theme: 'ai',
    content: {
      intro: 'AI maakt data, kennis en procesinformatie bruikbaar voor betere beslissingen in onderwijs, onderzoek en maakindustrie.',
      detail: 'Deze route verbindt het HAN Datalab, de lectoraten Applied Data Science & AI en Data & Knowledge Engineering, cursussen voor werkenden en praktijkcases rond sensordata, datamanagement en digital factories.',
      highlights: ['HAN Datalab', 'Applied Data Science & AI', 'Data & Knowledge Engineering', 'Cursussen'],
      applications: ['Roadsense', 'The Organized Digital Factory', 'AI in de praktijk'],
      sourceLabel: 'HAN ADS&AI, DKE, ICT-cursussen en Datalab',
      image: oldImages.aiMain,
      relatedItems: ['Datalab', 'Cursussen', 'Cases'],
    },
    children: [
      {
        id: 'ai-adsai',
        title: 'Lectoraat Applied Data Science & AI',
        color: '#FF3344',
        gradient: 'from-red-400 to-red-600',
        theme: 'ai',
        content: {
          intro: 'Erwin Folmer is lector Applied Data Science & AI. Het lectoraat ontwikkelt en deelt kennis over data science en AI voor concrete toepassingen.',
          detail: 'Het lectoraat is aanjager, verbinder en kennisdrager voor data science, knowledge graphs, federatie van data, data spaces en AI. Binnen iXperium Smart Industry sluiten vooral Roadsense en The Organized Digital Factory aan op sensordata, datakwaliteit en realtime besluitvorming.',
          highlights: ['Erwin Folmer, lector', 'Data Science', 'Knowledge Graphs', 'FAIR data'],
          applications: ['Roadsense', 'The Organized Digital Factory', 'AI-toepassingen'],
          sourceLabel: 'HAN Applied Data Science & AI',
          image: hanImages.erwinFolmer,
          relatedItems: ['Datalab', 'Cases'],
        },
      },
      {
        id: 'ai-dke',
        title: 'Lectoraat DKE',
        color: '#FFA033',
        gradient: 'from-orange-400 to-orange-600',
        theme: 'ai',
        content: {
          intro: 'Stijn Hoppenbrouwers is lector Data & Knowledge Engineering. Het lectoraat onderzoekt mensgericht omgaan met data, informatie en kennis.',
          detail: 'DKE past inzichten uit data-, informatie- en taalwetenschap toe in informatie- en kennissystemen. Relevant voor deze route zijn DEMAND, waarin organisaties methoden en tooling krijgen voor complexe dataketens, en Flexibele werkinstructies voor contextgevoelige kennis op de werkvloer.',
          highlights: ['Stijn Hoppenbrouwers, lector', 'Data Engineering & Management', 'Knowledge Engineering', 'Conceptual Modelling'],
          applications: ['DEMAND', 'Flexibele werkinstructies', 'Data- & kennismanagement'],
          sourceLabel: 'HAN Data & Knowledge Engineering',
          image: hanImages.stijnHoppenbrouwers,
          relatedItems: ['Cases', 'Cursussen'],
        },
      },
      {
        id: 'ai-praktijk',
        title: 'Cursussen',
        color: '#FF4400',
        gradient: 'from-red-500 to-orange-500',
        theme: 'ai',
        content: {
          intro: 'Cursussen voor werkenden maken AI en data direct toepasbaar in de eigen praktijk.',
          detail: 'Binnen het ICT-aanbod voor werkenden staan onder Cursussen AI en Data onder andere AI in de praktijk, Data-analyse en Datamanagement. Daarmee kunnen professionals starten met AI, data beter analyseren en data slimmer organiseren, koppelen en inzetten.',
          highlights: ['AI in de praktijk', 'Data-analyse', 'Datamanagement'],
          applications: ['AI-introductie', 'Inzichten uit data', 'Data organiseren'],
          sourceLabel: 'HAN ICT-cursussen voor werkenden',
          image: oldImages.aiMain,
          relatedItems: ['Datalab', 'Cases'],
        },
      },
      {
        id: 'ai-datalab',
        title: 'Datalab',
        color: '#FFD700',
        gradient: 'from-yellow-400 to-orange-400',
        theme: 'ai',
        content: {
          intro: 'Het HAN Datalab is de plek waar data science en AI zichtbaar en praktisch worden.',
          detail: 'De Datalab-website presenteert onderzoeksdemo’s, projecten en tools. In de kiosk kan dit landen als een 75 inch tools-overzicht: bezoekers zien welke AI-tools, datasets en prototypes beschikbaar zijn en hoe studenten, onderzoekers en mkb-partners daarmee praktijkvragen oplossen.',
          highlights: ['Datalab website', 'Tools op 75 inch', 'Mkb-vraagstukken'],
          applications: ['AI tools verkennen', 'Projectdemo’s tonen', 'Supportmoment plannen'],
          sourceLabel: 'HAN Datalab portfolio',
          image: oldImages.smartIndustryWide,
          relatedItems: ['Toolkit', 'Cursussen'],
        },
      },
      {
        id: 'ai-toolkit',
        title: 'Toolkit',
        color: '#C69E00',
        gradient: 'from-yellow-600 to-orange-500',
        theme: 'ai',
        content: {
          intro: 'De toolkit vertaalt onderzoek en labs naar toepasbare tools, stappen en experimenten.',
          detail: 'Bedrijven kunnen vanuit een vraagstuk naar dataset, modelkeuze, prototype en validatie bewegen. De 75 inch tools-weergave van het Datalab kan hierbij als startpunt dienen voor gesprek, demonstratie en selectie van passende AI-hulpmiddelen.',
          highlights: ['Vraagarticulatie', 'Toolselectie', 'Prototype-aanpak'],
          applications: ['AI-scan', 'Modelverkenning', 'Datakwaliteit'],
          sourceLabel: 'HAN Datalab en iXperium Smart Industry',
          image: oldImages.aiTransport,
          relatedItems: ['Cases', 'Datalab'],
        },
      },
      {
        id: 'ai-cases',
        title: 'Cases',
        color: '#FB3E0F',
        gradient: 'from-orange-500 to-red-500',
        theme: 'ai',
        content: {
          intro: 'De AI-cases laten zien hoe data science en AI waarde toevoegen in echte productie- en serviceprocessen.',
          detail: 'Roadsense gebruikt sensordata uit trailers om onderhoud en wegkwaliteit beter te begrijpen. The Organized Digital Factory ontwikkelt een Operations Digital Twin voor mkb-maakbedrijven, zodat planning en besturing realtime kunnen reageren op veranderingen.',
          highlights: ['Roadsense', 'The Organized Digital Factory'],
          applications: ['Sensordata', 'Realtime planning', 'Operations Digital Twin'],
          sourceLabel: 'HAN ADS&AI en DKE onderzoek',
          image: oldImages.aiRoadsense,
          relatedItems: ['Toolkit', 'Cursussen'],
        },
      },
    ],
  },
  {
    id: 'xr',
    title: 'XR & Human Machine Interaction',
    color: '#46B469',
    gradient: 'from-green-500 to-lime-500',
    theme: 'xr',
    content: {
      intro: 'XR en HMI maken digitale ondersteuning zichtbaar, testbaar en bruikbaar voor mensen op de werkvloer.',
      detail: 'Deze route koppelt Media Design, Lean en het Usability Lab aan flexibele werkinstructies. De nadruk ligt op mensgerichte interactie, AR-ondersteuning en gebruikersonderzoek voordat nieuwe technologie in assemblageprocessen wordt ingevoerd.',
      highlights: ['Media Design onderzoekslijnen', 'Flexibele werkinstructies', 'Usability Lab'],
      applications: ['AR-werkinstructies', 'Gebruikersonderzoek', 'HMI-validatie'],
      sourceLabel: 'HAN Media Design, Lean en Usability Lab',
      image: oldImages.xrHeadset,
      relatedItems: ['Usability Lab', 'Toolkit', 'Cases'],
    },
    children: [
      {
        id: 'xr-media',
        title: 'Lectoraat Media Design',
        color: '#46B469',
        gradient: 'from-green-400 to-green-600',
        theme: 'xr',
        content: {
          intro: 'Lectoraat Media Design onderzoekt hoe digitale systemen begrijpelijk, passend en betekenisvol worden voor gebruikers.',
          detail: 'De onderzoekslijnen zijn Blended Realities, Conversational Interfaces, Playful and Persuasive Design en Inclusive Digital Design and Engineering. Voor iXperium Smart Industry sluit vooral Flexibele werkinstructies aan: digitale instructies die contextgevoelig, flexibel en bruikbaar zijn in een omgeving met productvariëteit.',
          highlights: ['Blended Realities', 'Conversational Interfaces', 'Playful and Persuasive Design', 'Inclusive Digital Design'],
          applications: ['Flexibele werkinstructies', 'Prototyping', 'Gebruikerstests'],
          sourceLabel: 'HAN Media Design',
          image: oldImages.xrAlliander,
          relatedItems: ['Usability Lab', 'Cases'],
        },
      },
      {
        id: 'xr-lean',
        title: 'Lectoraat LEAN',
        color: '#A0EA00',
        gradient: 'from-lime-400 to-green-500',
        theme: 'xr',
        content: {
          intro: 'Lectoraat LEAN verbindt slim organiseren met smart technologie in manufacturing.',
          detail: 'Voor XR/HMI zijn vooral Flexibele werkinstructies en RAAK Augmented Reality in assemblageprocessen relevant. Het gaat om digitale ondersteuning die medewerkers helpt in variabele assemblage, zonder de menselijke maat en procesverbetering uit het oog te verliezen.',
          highlights: ['Flexibele werkinstructies', 'RAAK augmented reality', 'Smart factory'],
          applications: ['Werkinstructies', 'Assemblageondersteuning', 'Continu verbeteren'],
          sourceLabel: 'HAN Lean / World Class Performance',
          image: oldImages.smartIndustry,
          relatedItems: ['Cases', 'Toolkit'],
        },
      },
      {
        id: 'xr-usability',
        title: 'Usability Lab',
        color: '#6DB600',
        gradient: 'from-lime-500 to-green-600',
        theme: 'xr',
        content: {
          intro: 'Het Usability Lab is een testomgeving voor gebruikersonderzoek, observatie en interfacevalidatie.',
          detail: 'Met observatiespiegel, microfoons, bestuurbare camera’s en eyetracking kunnen deelnemers real-time worden gevolgd. Daardoor kunnen apps, websites, video’s, instructies en XR-prototypes getest worden via bijvoorbeeld usabilitytests, A/B-tests, focusgroepen of co-creatiesessies.',
          highlights: ['Eyetracking', 'Observatiespiegel', 'Gebruikersonderzoek'],
          applications: ['Interfacevalidatie', 'A/B-test', 'Co-creatiesessie'],
          sourceLabel: 'HAN MediaLab Usability Lab',
          image: oldImages.xrAllianderDetail,
          relatedItems: ['Lectoraat Media Design', 'Cases'],
        },
      },
      {
        id: 'xr-toolkit',
        title: 'Toolkit',
        color: '#9ABF49',
        gradient: 'from-lime-400 to-green-400',
        theme: 'xr',
        content: {
          intro: 'De XR/HMI-toolkit helpt om van werkproces naar prototype, gebruikerstest en implementatie te gaan.',
          detail: 'De toolkit bundelt ontwerpvragen, Lean-procesvragen, testvormen en technische keuzes voor AR, VR, scherminterfaces en flexibele instructies die in productieomgevingen bruikbaar moeten blijven.',
          highlights: ['Prototype canvas', 'Gebruikertest', 'AR-keuze'],
          applications: ['AR workflow', 'VR training', 'HMI review'],
          sourceLabel: 'HAN Media Design en Lean onderzoek',
          image: oldImages.xrHeadset,
          relatedItems: ['Usability Lab', 'Cases'],
        },
      },
      {
        id: 'xr-cases',
        title: 'Cases',
        color: '#2E8B57',
        gradient: 'from-green-600 to-emerald-600',
        theme: 'xr',
        content: {
          intro: 'De XR/HMI-case is Flexibele werkinstructies: ondersteuning voor assemblagewerk in een omgeving met variëteit.',
          detail: 'De case onderzoekt hoe werkinstructies contextgevoelig en flexibel gemaakt en gebruikt kunnen worden. Media Design brengt gebruikers en interactie in, Lean brengt de proces- en assemblageblik in.',
          highlights: ['Flexibele werkinstructies', 'Assemblage', 'Contextgevoelig'],
          applications: ['Operator support', 'AR-instructies', 'Werken met variatie'],
          sourceLabel: 'HAN Media Design, DKE en Lean onderzoek',
          image: oldImages.xrAlliander,
          relatedItems: ['Toolkit', 'Lectoraat Media Design'],
        },
      },
    ],
  },
  {
    id: 'twin',
    title: 'Digital Twin',
    color: '#1E90FF',
    gradient: 'from-blue-500 to-cyan-500',
    theme: 'twin',
    content: {
      intro: 'Digital twins verbinden fysieke processen, data en simulatie tot een actueel beeld van productie en assemblage.',
      detail: 'Deze route legt de nadruk op Lean-projecten zoals The Organized Digital Factory en Towards the digital factory, aangevuld met USAC als leer- en probeeromgeving waar digital twins, AR-instructies en slimme assemblage samenkomen.',
      highlights: ['The Organized Digital Factory', 'Towards the digital factory', 'USAC'],
      applications: ['Realtime planning', 'What-if simulatie', 'Procesverbetering'],
      sourceLabel: 'HAN Lean, ADS&AI en iXperium Smart Industry',
      image: oldImages.twinMain,
      relatedItems: ['USAC', 'Toolkit', 'Cases'],
    },
    children: [
      {
        id: 'twin-lean',
        title: 'Lectoraat LEAN',
        color: '#1E90FF',
        gradient: 'from-blue-400 to-blue-600',
        theme: 'twin',
        content: {
          intro: 'Lectoraat LEAN onderzoekt hoe digitale middelen productieprocessen korter, betrouwbaarder en beter bestuurbaar maken.',
          detail: 'Binnen Digital Twin zijn The Organized Digital Factory en Towards the digital factory de belangrijkste projecten. Ze richten zich op Operations Digital Twins, planning en besturing van high variety low volume productieprocessen.',
          highlights: ['The Organized Digital Factory', 'Towards the digital factory', 'High variety low volume'],
          applications: ['Doorlooptijd', 'Planning en besturing', 'Procesinzicht'],
          sourceLabel: 'HAN Lean / World Class Performance',
          image: oldImages.twinGoma,
          relatedItems: ['USAC', 'Toolkit'],
        },
      },
      {
        id: 'twin-dke',
        title: 'Lectoraat DKE',
        color: '#1C92AF',
        gradient: 'from-cyan-500 to-blue-500',
        theme: 'twin',
        content: {
          intro: 'DKE brengt de data- en kenniskant van digital twins in beeld.',
          detail: 'Een goede twin vraagt om heldere datamodellen, expliciete kennis, conceptueel modelleren en bruikbare visualisaties. DKE levert methoden om die informatie betrouwbaar te beheren en te koppelen aan de werkpraktijk.',
          highlights: ['Datamodellen', 'Kennisrepresentatie', 'Conceptueel modelleren'],
          applications: ['Twin architectuur', 'Conceptueel model', 'Kennisplatform'],
          sourceLabel: 'HAN Data & Knowledge Engineering',
          image: oldImages.twinResult,
          relatedItems: ['Lectoraat ADSAI', 'Cases'],
        },
      },
      {
        id: 'twin-adsai',
        title: 'Lectoraat ADSAI',
        color: '#0088FF',
        gradient: 'from-blue-500 to-cyan-600',
        theme: 'twin',
        content: {
          intro: 'Applied Data Science & AI ontwikkelt onder meer Operations Digital Twin toepassingen voor mkb-maakbedrijven.',
          detail: 'De focus ligt op realtime procesbeheersing: optimaal plannen, reageren op wijzigingen en data gebruiken om doorlooptijden kort en betrouwbaar te houden. Daarmee sluit ADS&AI direct aan op The Organized Digital Factory.',
          highlights: ['Operations Digital Twin', 'Realtime procesbeheersing', 'Mkb-maakbedrijven'],
          applications: ['Planning', 'Scenario-analyse', 'Beslisondersteuning'],
          sourceLabel: 'HAN Applied Data Science & AI',
          image: oldImages.twinGomaDetail,
          relatedItems: ['USAC', 'Toolkit'],
        },
      },
      {
        id: 'twin-usac',
        title: 'USAC',
        color: '#20B2AA',
        gradient: 'from-teal-400 to-cyan-500',
        theme: 'twin',
        content: {
          intro: 'USAC is de Smart U-Shaped Assembly Cell: een leer- en probeeromgeving voor slimme assemblage.',
          detail: 'De USAC combineert Lean-principes met technologie zoals AR-instructies, cobots, AGV-ideeën en digital twins. Bedrijven, studenten en onderzoekers testen hoe assemblageprocessen met veel variatie beter ondersteund kunnen worden.',
          highlights: ['U-vormige cel', 'AR-instructies', 'Digital twin'],
          applications: ['Assemblage met hoge variatie', 'Operator support', 'Doorvoeroptimalisatie'],
          sourceLabel: 'HAN iXperium Smart Industry en USAC',
          image: oldImages.smartIndustryWide,
          relatedItems: ['Toolkit', 'Cases'],
        },
      },
      {
        id: 'twin-toolkit',
        title: 'Toolkit',
        color: '#87CEFA',
        gradient: 'from-sky-300 to-blue-400',
        theme: 'twin',
        content: {
          intro: 'De Digital Twin-toolkit helpt om fysieke processen te vertalen naar data, modellen en simulaties.',
          detail: 'De toolkit ondersteunt de stap van digital shadow naar digital twin: meten, modelleren, visualiseren, simuleren en terugkoppelen naar de echte werkvloer. In de context van Lean gaat het vooral om betere planning, kortere doorlooptijden en beheersbare productievariatie.',
          highlights: ['Digital shadow', 'Modelvorming', 'Simulatie'],
          applications: ['Proceskaart', 'Sensorplan', 'Twin prototype'],
          sourceLabel: 'HAN Lean en iXperium Smart Industry',
          image: oldImages.twinMain,
          relatedItems: ['Cases', 'USAC'],
        },
      },
      {
        id: 'twin-cases',
        title: 'Cases',
        color: '#3022B2',
        gradient: 'from-blue-700 to-indigo-600',
        theme: 'twin',
        content: {
          intro: 'Digital Twin-cases tonen hoe simulatie, planning en echte productieprocessen elkaar versterken.',
          detail: 'De belangrijkste cases in deze route zijn The Organized Digital Factory en Towards the digital factory. Beide richten zich op productieomgevingen waar realtime inzicht, planning en procesbesturing verschil maken.',
          highlights: ['The Organized Digital Factory', 'Towards the digital factory'],
          applications: ['Operations Digital Twin', 'Virtuele testomgeving', 'Industriele demonstratie'],
          sourceLabel: 'HAN Lean / World Class Performance',
          image: oldImages.twinResult,
          relatedItems: ['Toolkit', 'Lectoraat LEAN'],
        },
      },
    ],
  },
  {
    id: 'rapid',
    title: 'Rapid Prototyping & Additive Manufacturing',
    color: '#E9CE03',
    gradient: 'from-yellow-400 to-orange-500',
    theme: 'rapid',
    content: {
      intro: 'Rapid prototyping en additive manufacturing brengen ideeen snel van digitaal ontwerp naar tastbaar prototype.',
      detail: 'In het iXperium en HAN FabLab ervaren bedrijven hoe 3D-printen, digitale fabricage en materiaalexperimenten kunnen helpen bij prototyping, maatwerk en steeds vaker ook industriele toepassingen.',
      highlights: ['HAN FabLab', '3D-printers', 'Design-build-test'],
      applications: ['Functionele prototypes', 'Maatwerk', 'Kleine series'],
      sourceLabel: 'HAN Additive Manufacturing en iXperium',
      image: oldImages.additivePrinter,
      relatedItems: ['FabLab', 'Toolkit', 'Cases'],
    },
    children: [
      {
        id: 'rapid-fablab',
        title: 'FabLab',
        color: '#E9CE03',
        gradient: 'from-yellow-400 to-yellow-600',
        theme: 'rapid',
        content: {
          intro: 'Het HAN FabLab is de digitale werkplaats voor maken, testen en leren met fabricagetechnieken.',
          detail: 'Tijdens de iXperium-tour staan in het FabLab fabricagetechnieken zoals 3D-printen centraal. Bedrijven kunnen er zelf ervaren hoe grondstoffen en ontwerpen tot prototypes worden verwerkt.',
          highlights: ['Digitale werkplaats', '3D-printen', 'Materiaalexperiment'],
          applications: ['Prototypebouw', 'Onderwijsprojecten', 'Maakindustrie demo'],
          sourceLabel: 'HAN iXperium Smart Industry en FabLab',
          image: oldImages.additivePrinter,
          relatedItems: ['Toolkit', 'Cases'],
        },
      },
      {
        id: 'rapid-toolkit',
        title: 'Toolkit',
        color: '#FFA914',
        gradient: 'from-orange-400 to-yellow-500',
        theme: 'rapid',
        content: {
          intro: 'De toolkit helpt om van ontwerpprobleem naar maakbaar prototype te gaan.',
          detail: 'De aanpak combineert materiaalkeuze, ontwerpregels, testscenario’s en snelle iteraties. Zo wordt additive manufacturing praktisch en toepasbaar voor mkb-vragen.',
          highlights: ['Materiaalkeuze', 'Ontwerpregels', 'Itereren'],
          applications: ['Maakbaarheidsscan', 'Prototype sprint', 'Testopstelling'],
          sourceLabel: 'iXperium Smart Industry projectdocument',
          image: oldImages.additivePrinter,
          relatedItems: ['FabLab', 'Cases'],
        },
      },
      {
        id: 'rapid-cases',
        title: 'Cases',
        color: '#DBB600',
        gradient: 'from-yellow-500 to-amber-600',
        theme: 'rapid',
        content: {
          intro: 'Cases laten zien waar digitale fabricage verschil maakt: sneller leren, beter testen en slimmer produceren.',
          detail: 'Additive manufacturing ontwikkelt zich van niche voor prototyping naar hoogwaardige industriele toepassingen. De cases tonen hoe samenwerking en kennisdeling die stap toegankelijker maken.',
          highlights: ['Van niche naar industrie', 'Kennisdeling', 'Testen met gebruikers'],
          applications: ['3D-geprinte hulpmiddelen', 'Productvalidatie', 'Maatwerkproductie'],
          sourceLabel: 'HAN Additive Manufacturing',
          image: oldImages.additiveCase,
          relatedItems: ['Toolkit', 'FabLab'],
        },
      },
    ],
  },
  {
    id: 'robotics',
    title: 'Robotics',
    color: '#FF2AD4',
    gradient: 'from-fuchsia-500 to-cyan-400',
    theme: 'robotics',
    content: {
      intro: 'Robotics verbindt mobiele robots, cobots, autonome voertuigen en mens-machine samenwerking in echte labs.',
      detail: 'Robotics@HAN biedt faciliteiten voor onderzoek en onderwijs: serverkracht, Mobile Robotics Lab, Lab Autonomous Vehicles, zorgrobotica en USAC-opstellingen met delta pickers en cobots.',
      highlights: ['Mobile Robotics Lab', 'Autonomous Vehicles', 'Cobots & USAC'],
      applications: ['ROS ontwikkeling', 'Autonoom testen', 'Slimme assemblage'],
      sourceLabel: 'Robotics@HAN faciliteiten',
      image: oldImages.smartIndustryWide,
      relatedItems: ['Mobile Robotics Lab', 'Cobots & USAC', 'Test- en meetsystemen'],
    },
    children: [
      {
        id: 'robotics-servers',
        title: 'Robotics@HAN servers',
        color: '#FF2AD4',
        gradient: 'from-fuchsia-500 to-purple-600',
        theme: 'robotics',
        content: {
          intro: 'On-premise computerkracht voor robotica onderwijs, onderzoek en projectpartners.',
          detail: 'De servers ondersteunen simulaties, AI training, robotbesturing, Hardware in the Loop en digital twinning. Ze zijn breedbandig verbonden met het Mobile Robotics Lab en Lab Autonomous Vehicles.',
          highlights: ['Control Center', 'AI training', 'Hardware in the Loop'],
          applications: ['Simulatie', 'Robotbesturing', 'Digital twinning'],
          sourceLabel: 'Robotics@HAN faciliteiten',
          image: oldImages.smartIndustryWide,
          relatedItems: ['Mobile Robotics Lab', 'Lab Autonomous Vehicles'],
        },
      },
      {
        id: 'robotics-mobile-lab',
        title: 'Mobile Robotics Lab',
        color: '#00F5FF',
        gradient: 'from-cyan-300 to-fuchsia-500',
        theme: 'robotics',
        content: {
          intro: 'Werkplekken en een testruimte voor mobiele robots met nauwkeurige realtime lokalisatie.',
          detail: 'Het lab gebruikt OptiTrack motion capture. Lokalisatie kan via wifi als ROS topic naar robots worden gepubliceerd, eventueel als ge-emuleerde GPS. PTZ-camera’s maken tests op afstand zichtbaar.',
          highlights: ['OptiTrack', 'ROS topics', 'PTZ camera’s'],
          applications: ['Robotlokalisatie', 'Testopnames', 'Mobiele robotontwikkeling'],
          sourceLabel: 'Robotics@HAN faciliteiten',
          image: oldImages.smartIndustry,
          relatedItems: ['Robotics@HAN servers', 'Test- en meetsystemen'],
        },
      },
      {
        id: 'robotics-autonomous-vehicles',
        title: 'Lab Autonomous Vehicles',
        color: '#9D4DFF',
        gradient: 'from-violet-500 to-cyan-400',
        theme: 'robotics',
        content: {
          intro: 'Garageruimte en buitentestlocaties voor full-scale autonome voertuigen en grotere mobiele robots.',
          detail: 'Het lab heeft grote roldeuren, toegang tot buitentests en een nabij parkeerdek van 165 bij 10 meter. Een LiDAR-gebaseerde referentiekaart kan gebruikt worden voor lokalisatie.',
          highlights: ['Full-scale testen', 'Buitenterrein', 'LiDAR referentiekaart'],
          applications: ['Autonome voertuigen', 'Mobiele robots', 'Navigatievalidatie'],
          sourceLabel: 'Robotics@HAN faciliteiten',
          image: oldImages.smartIndustry,
          relatedItems: ['HAN Streetdrone', 'Mobile Robotics Lab'],
        },
      },
      {
        id: 'robotics-cobots-usac',
        title: 'Cobots & USAC',
        color: '#C7FF2E',
        gradient: 'from-lime-300 to-fuchsia-500',
        theme: 'robotics',
        content: {
          intro: 'De USAC is een slimme productieomgeving met robotica-oplossingen voor flexibele assemblage.',
          detail: 'In de USAC wordt gewerkt met delta pickers, cobots, vision-systemen, grijpers en een gekoppelde IT-structuur. Bedrijven en studenten leren er hoe automatisering werkt in productie met veel variatie.',
          highlights: ['Delta pickers', 'Cobots', 'Operations digital twin'],
          applications: ['Monteren', 'Controleren', 'Proces stroomlijnen'],
          sourceLabel: 'HAN USAC en cobot-artikel',
          image: oldImages.smartIndustryWide,
          relatedItems: ['Robotics@HAN servers', 'iXperium Smart Industry'],
        },
      },
      {
        id: 'robotics-health-carebots',
        title: 'Zorgrobotica',
        color: '#FF6BE8',
        gradient: 'from-pink-400 to-cyan-400',
        theme: 'robotics',
        content: {
          intro: 'Zorgrobotica onderzoekt het samenspel tussen technologie, acceptatie en mensgerichte zorgprocessen.',
          detail: 'Robotics@HAN koppelt zorgspecialisten, technici, IT’ers en processpecialisten. Studenten bouwden bijvoorbeeld een prototype logistieke zorgrobot als testplatform voor CareBOTS.',
          highlights: ['CareBOTS', 'Mens-machine acceptatie', 'Logistieke zorgrobot'],
          applications: ['Zorglogistiek', 'Robotacceptatie', 'SLAM en navigatie'],
          sourceLabel: 'Robotics@HAN',
          image: oldImages.smartIndustry,
          relatedItems: ['iXperium Health', 'Test- en meetsystemen'],
        },
      },
      {
        id: 'robotics-test-systems',
        title: 'Test- en meetsystemen',
        color: '#50FFB8',
        gradient: 'from-emerald-300 to-fuchsia-500',
        theme: 'robotics',
        content: {
          intro: 'Meet- en testsystemen maken robotgedrag controleerbaar in lab- en praktijkscenario’s.',
          detail: 'Denk aan mobiele motion capture, RTK-GPS, sensorplatforms, dummies voor verkeersscenario’s en perception kits. Deze middelen helpen om testen herhaalbaar en uitlegbaar te maken.',
          highlights: ['Motion capture', 'RTK-GPS', 'Perception kits'],
          applications: ['Validatie', 'Scenario testen', 'Sensorvergelijking'],
          sourceLabel: 'Robotics@HAN faciliteiten',
          image: oldImages.smartIndustryWide,
          relatedItems: ['Mobile Robotics Lab', 'Lab Autonomous Vehicles'],
        },
      },
    ],
  },
];
